# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2816a61f18b691a903df849f9278ce30"
application_url = "https://example.com"
embedded = true
name = "Gift Message & Wrapping"

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks"
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

application_url = "https://example.com"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "/api/gift-settings"
prefix = "apps"
subpath = "gift-settings"