client_id = "2816a61f18b691a903df849f9278ce30"
application_url = "https://gift-message-wrapping-7rdk.vercel.app"
embedded = true
name = "Gift Message & Wrapping"

[access_scopes]
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://gift-message-wrapping-7rdk.vercel.app/auth/callback",
  "https://gift-message-wrapping-7rdk.vercel.app/auth/shopify/callback",
  "https://gift-message-wrapping-7rdk.vercel.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "/api/gift-settings"
prefix = "apps"
subpath = "gift-settings"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact"
  ]