// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/gift-settings": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/webhooks": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/print/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/app/messages": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/wrapping": {
    params: {};
  };
  "/app/orders": {
    params: {};
  };
  "/app/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/gift-settings" | "/auth/login" | "/webhooks" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/*" | "/app" | "/app/print/:orderId" | "/app/messages" | "/app/settings" | "/app/wrapping" | "/app/orders" | "/app/help";
  };
  "routes/api.gift-settings.jsx": {
    id: "routes/api.gift-settings";
    page: "/api/gift-settings";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/webhooks.jsx": {
    id: "routes/webhooks";
    page: "/webhooks" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/print/:orderId" | "/app/messages" | "/app/settings" | "/app/wrapping" | "/app/orders" | "/app/help";
  };
  "routes/app.print.$orderId.jsx": {
    id: "routes/app.print.$orderId";
    page: "/app/print/:orderId";
  };
  "routes/app.messages.jsx": {
    id: "routes/app.messages";
    page: "/app/messages";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.wrapping.jsx": {
    id: "routes/app.wrapping";
    page: "/app/wrapping";
  };
  "routes/app.orders.jsx": {
    id: "routes/app.orders";
    page: "/app/orders";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.help.jsx": {
    id: "routes/app.help";
    page: "/app/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.gift-settings": typeof import("./app/routes/api.gift-settings.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/webhooks": typeof import("./app/routes/webhooks.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.print.$orderId": typeof import("./app/routes/app.print.$orderId.jsx");
  "routes/app.messages": typeof import("./app/routes/app.messages.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.wrapping": typeof import("./app/routes/app.wrapping.jsx");
  "routes/app.orders": typeof import("./app/routes/app.orders.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.help": typeof import("./app/routes/app.help.jsx");
};